### ISSUE TITLE
Chinese characters

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-last-author#4]
It would be nice if the plugin could identify all the names in Chinese characters (and probably other languages where it would be needed), and then differentiate the way they are displayed.

In the normal mode (full first name), the name should be simply displayed without separator between the last name and the first name: `刘伟明` instead of `刘, 伟明`. Maybe make this an option in case some people still want to keep the separator with Chinese characters?

The option to display first names as initials does not work well with Chinese characters:
- `刘伟明` -> `刘, 伟.`
- `李军` -> `李, 军.`

The first name initials option should not affect the display of Chinese characters, where it should still display the full name normally.

**Comment by github-young** [comment]
That is an interesting issue as I never had items with Chinese authors.

I think it is good enough to keep the CJK author names as is because I am not quite familiar with adding more setting items in Zotero so I would not make such an option to keep the separators.

Now I made it display the full name of the CJK author names as you pointed out.

closed in [v2.1.0](https://github.com/github-young/zotero-last-author/releases/tag/v2.1.0)
