### ISSUE TITLE
Corresponding author

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-last-author#5]
Would it be possible to show the corresponding author(s) instead of the last author? They can often be different.
You mentioned the corresponding author in your post in the forum:
> I had the same need for displaying the last author (or the corresponding author) in an individual column

https://forums.zotero.org/discussion/comment/443921#Comment_443921

I guess the assumption in that sentence is that the corresponding author is the last author?

It may be too ambitious, but I still wanted to mention it in case there is an easy solution.
I understand that Zotero does not store that information, so it would need to be stored in some format.
Also, I do not know any way to retrieve automatically the corresponding author(s) information on a paper.
I will be glad to be pointed to some other existing resources.

**Comment by github-young** [comment]
Well, as you said, Zotero itself does not store any information about who is the corresponding author, so it is very difficult to achieve this feature within the scope of this plugin. After all, this plugin is designed to display the "last" author, and the "corresponding" author is kind of a by-product of it. I am closing it due to the inability of solution.
