### ISSUE TITLE
Initials of author names mixed with CJK characters

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-last-author#7]
Thank you very much again for the recent improvements!

For some journals, they mix the author names between the English name and the CJK characters.
This does not work well with the first name initials.

Examples:

This paper https://doi.org/10.1063/5.0162449
Has last author: `Deng`, `Daosheng (邓道盛)`
It is currently displayed as: `Deng, Daosheng(邓道盛)`
The expected result would be: `Deng, D.`

This paper: https://pubs.aip.org/aip/pof/article/35/8/082101/2905561/Dispensing-uniform-droplets-of-phosphate-buffer
Has last author: `Lee`, `Jinkee (이진기)`
It is curently displayed as: `Lee, J. (.`
The expected result would be: `Lee, J.`
I am not sure why this one is treated differently from the previous one.
Anyway, some special characters should probably be excluded from being valid initials, like the parenthesis here.

This paper: https://doi.org/10.1063/5.0129427
Has last author: `Thoraval`, `Marie-Jean (陶益壮)`
It is curently displayed as: `Thoraval, MarieJean(陶益壮)`
The expected result would be: `Thoraval, M.-J.`

Strictly speaking, this is probably wrong to put the CJK characters in the first name field. But considering that Zotero (as most publishers) cannot handle multilingual metadata at the moment, this is already not too bad.

**Comment by github-young** [comment]
Fixed in [v2.1.1](https://github.com/github-young/zotero-last-author/releases/tag/v2.1.1).

According to the 3 examples you gave, I just ignore all content after the "(" character.

But as you said:

> Strictly speaking, this is probably wrong to put the CJK characters in the first name field.

It is indeed a problem that happens when the original data is parsed by the Zotero browser plugin. So it is better, logically, to file an issue in that repo and hope someday it can be solved.
